package com.tomtruyen.automation.features.triggers

enum class TriggerType {
    CHARGE_STATE,
    TIME_BASED,
    BATTERY_LEVEL,
    POWER_CONNECTION,
    BATTERY_SAVER_STATE,
    APPLICATION_LIFECYCLE,
    NOTIFICATION_RECEIVED,
    WIFI_SSID_IN_RANGE,
    GEOFENCE,
    NETWORK_CONNECTIVITY,
    BLUETOOTH_DEVICE_CONNECTION,
    HEADPHONE_CONNECTION,
    PACKAGE_CHANGED,
    TIME_ZONE_CHANGED,
    DO_NOT_DISTURB_MODE,
}
