package com.tomtruyen.automation.features.triggers.receiver

enum class TriggerReceiverKey {
    BATTERY_CHANGED,
    TIME_TICK,
    POWER_CONNECTION,
    BATTERY_SAVER,
    APPLICATION_LIFECYCLE,
    WIFI_SCAN,
    GEOFENCE,
    NETWORK_CONNECTIVITY,
    BLUETOOTH_DEVICE_CONNECTION,
    HEADPHONE_CONNECTION,
    PACKAGE_CHANGED,
    TIME_ZONE_CHANGED,
    DO_NOT_DISTURB_MODE,
}
